[build]
base = "apps/web"
command = "pnpm install --frozen-lockfile && pnpm build"
publish = "apps/web/dist/client"

[functions]
directory = "apps/web/dist/server"

[[plugins]]
package = "@netlify/plugin-functions"
